#[cfg(test)]
mod tests;

use anyhow::{Result, ensure};

use crate::plugin::{
    splits::geometry::Track,
    track_source::{decode::decode_geometry, encode::encode_for_disk},
};

/// Name of the `<CustomVariable>` inside the `.lss` XML that holds the
/// canonical track geometry. Shared by the reader (lookup) and writer
/// (build + dedup compare).
pub const CUSTOM_VAR_NAME: &str = "ClassiCubeTrack";

/// Default label for the Start checkpoint, which has no `<Segment>` of
/// its own (see [`apply_labels`]). Matches the conventional Start label
/// used elsewhere (fixture, status display).
const START_LABEL: &str = "Start";

/// Serialize a `Track`'s geometry to the canonical readable text stored
/// in the `ClassiCubeTrack` custom variable: newline-joined bare `LS …`
/// lines (`LS v<n>` / `LS cp …` / `LS map …` / `LS pause …` /
/// `LS unpause …` / `LS end`), with no title and no labels. The title
/// lives in the `.lss` `<CategoryName>` and labels in the `<Segment>`
/// elements instead, so a rename-only or label-only change yields
/// identical text and the writer's dedup gate skips it. livesplit-core
/// XML-escapes the value on save and unescapes it on load.
pub fn serialize_canonical(track: &Track) -> Result<String> {
    Ok(encode_for_disk(track)?.join("\n"))
}

/// Parse the stored `ClassiCubeTrack` value (readable `LS …` geometry)
/// plus the `.lss` `<CategoryName>` title and `<Segment>` names into a
/// runtime `Track`. The geometry decoder yields a name-less, label-less
/// `Track`; [`apply_labels`] attaches the segment names (one per
/// non-Start checkpoint, defaulting the Start to [`START_LABEL`]) and the
/// `title` (from `<CategoryName>`) overwrites the empty name. A legacy
/// base64/postcard value, a payload still carrying an `LS title` line, or
/// any non-`LS` text fails inside [`decode_geometry`] -- the clean-break
/// behavior: old files are skipped and regenerated by reload + save.
pub fn parse(value: &str, title: String, labels: Vec<String>) -> Result<Track> {
    let geometry = decode_geometry(value)?;
    let mut track = apply_labels(geometry, labels)?;
    track.name = title;
    Ok(track)
}

/// Attach `.lss` segment labels to a label-less geometry `Track`.
/// Segments cover every checkpoint *except* the implicit Start at index
/// 0 -- pressing Start is the run-start action, not a named split -- so
/// the reader expects one label per non-Start checkpoint and gives the
/// Start a default [`START_LABEL`]. Empty segment names get a generated
/// `"split <i>"` placeholder so the runtime invariant "label is
/// non-empty" holds.
fn apply_labels(geometry: Track, labels: Vec<String>) -> Result<Track> {
    let n = geometry.checkpoints.len();
    ensure!(
        n >= 2,
        "track has {n} checkpoint(s); need at least 2 (Start + End)"
    );
    ensure!(
        labels.len() + 1 == n,
        "label count {} doesn't match split count {} (checkpoints after the Start)",
        labels.len(),
        n - 1
    );

    let mut labels = labels.into_iter();
    let checkpoints = geometry
        .checkpoints
        .into_iter()
        .enumerate()
        .map(|(i, mut cp)| {
            cp.label = if i == 0 {
                // The Start has no segment; give it a stable default.
                START_LABEL.to_owned()
            } else {
                // `next()` is guaranteed Some by the count check above.
                match labels.next() {
                    Some(s) if !s.trim().is_empty() => s,
                    _ => format!("split {i}"),
                }
            };
            cp
        })
        .collect();

    Ok(Track {
        name: geometry.name,
        checkpoints,
    })
}
